# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Sphinx setup
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

# Install build dependencies
conda:
  environment: environment.yml

# Install doc-building dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Specify the build process
build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  jobs:
    install:
      - bash ./linux_build.bash
      - pip install libcarna_python-*.whl