name: carnapy-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python ~=3.12
  - pybind11 <3
  - libcarna ==3.3.3
  - libgl-devel
  - libegl-devel
  - libopengl-devel
  - libglu
  - cxx-compiler
  - make
  - cmake
  - eigen >=3.0.5
  - pyyaml
  - setuptools
  - matplotlib-base  # for tests
  - scipy  # for tests
  - pip
  - pip:
    - numpngw ==0.1.4  # for tests and docs (writes APNG)
    - apng ==0.3.4  # for tests and docs (reads APNG)