name: libcarna-python-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python ~=3.12

  # ---------------------------------------------------------------------------
  # Build dependencies

  - pybind11 <3
  - libgl-devel
  - libegl-devel
  - libopengl-devel
  - libglu
  - cxx-compiler
  - make
  - cmake
  - eigen >=3.0.5
  - pyyaml
  - setuptools

  # ---------------------------------------------------------------------------
  # Runtime dependencies (general)

  - libcarna ==3.4.0
  - numpngw ==0.1.4  # writes APNG
  - scikit-video ==1.1.11  # API for ffmpeg
  - ffmpeg  # writes h264
  - scipy  # for `libcarna.data` and `libcarna.normalize_hounsfield_units`
  - scikit-image  # for `libcarna.data`
  - tifffile  # for `libcarna.data`
  - pooch  # for `libcarna.data`