name: carnapy-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python ~=3.12

  # ---------------------------------------------------------------------------
  # Build dependencies

  - pybind11 <3
  - libgl-devel
  - libegl-devel
  - libopengl-devel
  - libglu
  - cxx-compiler
  - make
  - cmake
  - eigen >=3.0.5
  - pyyaml
  - setuptools

  # ---------------------------------------------------------------------------
  # Runtime dependencies (general)
  - numpngw ==0.1.4  # writes APNG
  - libcarna ==3.3.3
  - scikit-video ==1.1.11  # API for ffmpeg
  - ffmpeg  # writes h264

  # ---------------------------------------------------------------------------
  # Runtime dependencies (tests)
  - matplotlib-base
  - scipy

  # ---------------------------------------------------------------------------
  # Runtime dependencies (examples/docs)
  - scikit-image

  # ---------------------------------------------------------------------------
  # pip dependencies
  - pip
  - pip:
    - apng ==0.3.4  # for tests (reads APNG)
    - pooch  # for examples/docs