name: Build and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          environment-file: environment.yml
          auto-activate-base: false
          python-version: ${{ inputs.python-version }}
          channels: conda-forge, bioconda
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true

      - name: Set environment variables
        run: echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV
        #shell: bash
        #run: echo "CONDA_PREFIX=$(conda info --json | jq -r '.active_prefix')" >> $GITHUB_ENV

      - name: Build dist
        run: python setup.py bdist_wheel
        env:
          PYBIND11_PREFIX: '${{ CONDA_PREFIX }}/share/cmake/pybind11'
          CMAKE_MODULE_PATH: '${{ CONDA_PREFIX }}/share/cmake/Modules'

      - name: Build and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
             dist

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install wheel
        run: pip install dist/*.whl

      - name: Test installation
        run: python -c "import libcarna; print(libcarna.version)"

      - name: Install dependencies
        run: pip install matplotlib-base

      - name: Run tests
        run: python -m unittest test

      - name: Run example notebooks
        run: jupyter nbconvert --execute --to notebook --inplace examples/*.ipynb