name: Build and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.python-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          python-version: ${{ inputs.python-version }}
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true

      - name: Set environment variables
        run: echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV

      - name: Build dist
        shell: bash
        run: ./linux_build.bash

      - name: Build and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
             dist

  test:
    needs: build
    name: Test ${{ inputs.python-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install wheel
        run: pip install dist/*.whl

      - name: Test installation
        run: python -c "import libcarna; print(libcarna.version)"

      - name: Install dependencies
        run: pip install matplotlib-base

      - name: Run tests
        run: python -m unittest test

      - name: Run example notebooks
        run: jupyter nbconvert --execute --to notebook --inplace examples/*.ipynb