name: Build and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true

      - name: Patch required Python version
        run: |
          sed -i "s|python .\+|python ==${{ inputs.python-version }}|g" environment.yml
          cat environment.yml

      - name: Create and validate conda environment
        shell: bash
        run: |
          conda env create -f environment.yml --prefix ./.env
          eval "$(conda shell.bash hook)"
          conda activate ./.env
          python -V
          python -c "import sys; v = sys.version_info; assert f'{v.major}.{v.minor}' == '${{ inputs.python-version }}'"

      - name: Build dist
        shell: bash
        run: ./linux_build.bash

      - name: Build and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ inputs.python-version }}
          path: |
             dist

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ inputs.python-version }}

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install wheel
        run: pip install dist/*.whl

      - name: Test installation
        run: python -c "import libcarna; print(libcarna.version)"

      - name: Install dependencies
        run: pip install matplotlib-base

      - name: Run tests
        run: python -m unittest test

      - name: Run example notebooks
        run: jupyter nbconvert --execute --to notebook --inplace examples/*.ipynb