name: Build and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true

      - name: Patch required Python version
        run: |
          sed -i "s|python .\+|python ==${{ inputs.python-version }}|g" environment.yml
          cat environment.yml

      - name: Create and validate conda environment
        shell: bash
        run: |
          conda env create -f environment.yml --prefix ./.env
          eval "$(conda shell.bash hook)"
          conda activate ./.env
          python -V
          python -c "import sys; v = sys.version_info; assert f'{v.major}.{v.minor}' == '${{ inputs.python-version }}'"

      - name: Build dist
        shell: bash
        run: ./linux_build.bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ inputs.python-version }}
          path: |
             dist

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ inputs.python-version }}

      - name: Prepare conda environment
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: test.yml
          contents: |
            name: test
            channels:
              - conda-forge
              - bioconda
            dependencies:
              - python ==${{ inputs.python-version }}
              - libcarna ==3.4.0
              - pip

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true
          channels: conda-forge, bioconda
          auto-activate-base: false
          activate-environment: test
          environment-file: test.yml

      - name: Validate Python version
        shell: bash
        run: |
          python -V
          python -c "import sys; v = sys.version_info; assert f'{v.major}.{v.minor}' == '${{ inputs.python-version }}'"

      - name: Install wheel
        run: pip install libcarna_python-*.whl

      - name: Test installation
        run: python -c "import libcarna; print(libcarna.version)"

      - name: Install dependencies for tests and examples
        run: |
          pip install -r test/requirements.txt
          pip install nbconvert

      - name: Run tests
        run: python -m unittest test

      - name: Run example notebooks
        run: nbconvert --execute --to notebook --inplace examples/*.ipynb