name: Build and Test

on:
  workflow_dispatch:

  push:
    branches: [ 'master', 'develop' ]
    paths-ignore:
      - 'docs/**'
      - '.git*'
      - 'LICENSE'
      - 'LICENSE-*'
      - 'README.md'

  pull_request:
    branches-ignore: [ 'master' ]

jobs:
  build_and_test:
    name: Build and Test ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}