name: Build and Test

on:
  push:
    branches:
      - 'master'
      - 'dev**'
    tags:
      - '**'

jobs:
  build_and_test:
    name: Build and Test ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}